# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf451a839569de3b562f635e80c82348ca8a5a98ff282ef515cb4a9f200b7fb086229027b92d15db564cf7fb5b8acdfba0b3486b476fa4df5f95a4f543684ae1

test:
  secret_key_base: e0404ba3268da18bbf74b6e60b75f733dd2036b6464209933c9b93deb874d57e8492030f2e584e0794aa4c712af914ae1aae8402a95cde91be4a02a9697a3f5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
